//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pomodoro.Bll.Provider.Mock.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pomodoro.Bll.Provider.Mock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;user&quot;: {
        ///            &quot;name&quot;: &quot;admin&quot;,
        ///            &quot;id&quot;: &quot;b41a9f1b-9c27-4985-9ba8-55d32614591d&quot;
        ///        },
        ///        &quot;title&quot;: &quot;Pomodoro1&quot;,
        ///        &quot;id&quot;: &quot;26b349d1-56d1-4678-8933-90fbd86c2667&quot;,
        ///        &quot;restDuration&quot;: &quot;00:15:00&quot;,
        ///        &quot;workDuration&quot;: &quot;01:15:00&quot;
        ///    },
        ///    {
        ///        &quot;user&quot;: {
        ///            &quot;name&quot;: &quot;user1&quot;,
        ///            &quot;id&quot;: &quot;5c8ecd57-7c0e-4f42-a936-85385bf6796f&quot;
        ///        },
        ///        &quot;title&quot;: &quot;Pomodoro2&quot;,
        ///        &quot;id&quot;: &quot;3100550e-a80d-405a-a19e-1a98cf2f4062&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pomodoros {
            get {
                return ResourceManager.GetString("pomodoros", resourceCulture);
            }
        }
    }
}
