//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pomodoro.Bll.Provider.Mock.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pomodoro.Bll.Provider.Mock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///    {
        ///        &quot;user&quot;: {
        ///            &quot;name&quot;: &quot;admin&quot;,
        ///            &quot;id&quot;: &quot;b41a9f1b-9c27-4985-9ba8-55d32614591d&quot;
        ///        },
        ///        &quot;title&quot;: &quot;Pomodoro1&quot;,
        ///        &quot;id&quot;: &quot;dcfc30f2-6049-4b73-b466-53899bffd593&quot;,
        ///        &quot;restDuration&quot;: {
        ///            &quot;minutes&quot;: 15,
        ///            &quot;hours&quot;: 0
        ///        },
        ///        &quot;workDuration&quot;: {
        ///            &quot;minutes&quot;: 0,
        ///            &quot;hours&quot;: 0
        ///        }
        ///    },
        ///    {
        ///        &quot;user&quot;: {
        ///            &quot;name&quot;: &quot;user1&quot;,
        ///            &quot;id&quot;: &quot;5c8ecd57-7c0e-4f42-a936-85385bf679 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string pomodoros {
            get {
                return ResourceManager.GetString("pomodoros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [  
        ///  {
        ///    &quot;user&quot;: {
        ///      &quot;name&quot;: &quot;admin&quot;,
        ///      &quot;id&quot;: &quot;b41a9f1b-9c27-4985-9ba8-55d32614591d&quot;
        ///    },
        ///    &quot;title&quot;: &quot;Pomodoro1&quot;,
        ///    &quot;id&quot;: &quot;7fa825a1-0309-4817-a9d1-2f75b5cce5c6&quot;,
        ///    &quot;restDuration&quot;: {
        ///      &quot;minutes&quot;: 15,
        ///      &quot;hours&quot;: 0
        ///    },
        ///    &quot;workDuration&quot;: {
        ///      &quot;minutes&quot;: 15,
        ///      &quot;hours&quot;: 1
        ///    }
        ///  },
        ///  {
        ///    &quot;user&quot;: {
        ///      &quot;name&quot;: &quot;user1&quot;,
        ///      &quot;id&quot;: &quot;5c8ecd57-7c0e-4f42-a936-85385bf6796f&quot;
        ///    },
        ///    &quot;title&quot;: &quot;Pomodoro2&quot;,
        ///    &quot;id&quot;: &quot;604031d9-6a61-46ae-8032-cfd778f785e8 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string pomodoros5 {
            get {
                return ResourceManager.GetString("pomodoros5", resourceCulture);
            }
        }
    }
}
