// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Pomodoro.Bll.Provider.MySql.Migrations
{
    [DbContext(typeof(PomodoroDbContext))]
    [Migration("20211114044829_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Pomodoro.Bll.Provider.MySql.Entity.Pomodoro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pomodoros");
                });

            modelBuilder.Entity("Pomodoro.Bll.Provider.MySql.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pomodoro.Bll.Provider.MySql.Entity.Pomodoro", b =>
                {
                    b.HasOne("Pomodoro.Bll.Provider.MySql.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Pomodoro.Bll.Provider.MySql.Entity.Duration", "RestDuration", b1 =>
                        {
                            b1.Property<Guid>("PomodoroId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Hours")
                                .HasColumnType("int")
                                .HasColumnName("RestHours");

                            b1.Property<int>("Minutes")
                                .HasColumnType("int")
                                .HasColumnName("RestMinutes");

                            b1.HasKey("PomodoroId");

                            b1.ToTable("Pomodoros");

                            b1.WithOwner()
                                .HasForeignKey("PomodoroId");
                        });

                    b.OwnsOne("Pomodoro.Bll.Provider.MySql.Entity.Duration", "WorkDuration", b1 =>
                        {
                            b1.Property<Guid>("PomodoroId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Hours")
                                .HasColumnType("int")
                                .HasColumnName("WorkHours");

                            b1.Property<int>("Minutes")
                                .HasColumnType("int")
                                .HasColumnName("WorkMinutes");

                            b1.HasKey("PomodoroId");

                            b1.ToTable("Pomodoros");

                            b1.WithOwner()
                                .HasForeignKey("PomodoroId");
                        });

                    b.Navigation("RestDuration")
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkDuration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
