// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SingleServiceApp.Providers.Statistics;

#nullable disable

namespace SingleServiceApp.Migrations.StatisticDb
{
    [DbContext(typeof(StatisticDbContext))]
    [Migration("20211226072614_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SingleServiceApp.Bll.Statistics.Statistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TagName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("TagName");

                    b.HasIndex("TitleId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("SingleServiceApp.Bll.Statistics.Tag", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("float");

                    b.HasKey("Name");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SingleServiceApp.Bll.Statistics.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TagName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("TagName");

                    b.ToTable("Title");
                });

            modelBuilder.Entity("SingleServiceApp.Providers.Statistics.Entity.ColorSql", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Argb")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("SingleServiceApp.Bll.Statistics.Statistic", b =>
                {
                    b.HasOne("SingleServiceApp.Bll.Statistics.Tag", "Tag")
                        .WithMany("Statistics")
                        .HasForeignKey("TagName")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SingleServiceApp.Bll.Statistics.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SingleServiceApp.Bll.Auth.UserEntry", "User", b1 =>
                        {
                            b1.Property<Guid>("StatisticId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StatisticId");

                            b1.ToTable("Statistics");

                            b1.WithOwner()
                                .HasForeignKey("StatisticId");
                        });

                    b.Navigation("Tag");

                    b.Navigation("Title");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SingleServiceApp.Bll.Statistics.Tag", b =>
                {
                    b.OwnsOne("SingleServiceApp.Bll.Auth.UserEntry", "User", b1 =>
                        {
                            b1.Property<string>("TagName")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TagName");

                            b1.ToTable("Tags");

                            b1.WithOwner()
                                .HasForeignKey("TagName");
                        });

                    b.Navigation("User");
                });

            modelBuilder.Entity("SingleServiceApp.Bll.Statistics.Title", b =>
                {
                    b.HasOne("SingleServiceApp.Providers.Statistics.Entity.ColorSql", "ColorSql")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SingleServiceApp.Bll.Statistics.Tag", "Tag")
                        .WithMany("Tittles")
                        .HasForeignKey("TagName");

                    b.Navigation("ColorSql");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SingleServiceApp.Bll.Statistics.Tag", b =>
                {
                    b.Navigation("Statistics");

                    b.Navigation("Tittles");
                });
#pragma warning restore 612, 618
        }
    }
}
