// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Statistic.Bll.Provider.MySql;

#nullable disable

namespace Statistic.Bll.Provider.MySql.Migrations
{
    [DbContext(typeof(StatisticDbContext))]
    [Migration("20211202050114_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Statistic.Bll.Provider.MySql.Entity.ColorSql", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Argb")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("Statistic.Bll.Provider.MySql.Entity.Statistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TittleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("TittleId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("Statistic.Bll.Provider.MySql.Entity.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Statistic.Bll.Provider.MySql.Entity.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("TagId");

                    b.ToTable("Title");
                });

            modelBuilder.Entity("Statistic.Bll.Provider.MySql.Entity.Statistic", b =>
                {
                    b.HasOne("Statistic.Bll.Provider.MySql.Entity.Tag", "Tag")
                        .WithMany("Statistics")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Statistic.Bll.Provider.MySql.Entity.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TittleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Statistic.Bll.Provider.MySql.Entity.User", "User", b1 =>
                        {
                            b1.Property<Guid>("StatisticId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UserName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StatisticId");

                            b1.ToTable("Statistics");

                            b1.WithOwner()
                                .HasForeignKey("StatisticId");
                        });

                    b.Navigation("Tag");

                    b.Navigation("Title");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Statistic.Bll.Provider.MySql.Entity.Tag", b =>
                {
                    b.OwnsOne("Statistic.Bll.Provider.MySql.Entity.User", "User", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UserName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TagId");

                            b1.ToTable("Tags");

                            b1.WithOwner()
                                .HasForeignKey("TagId");
                        });

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Statistic.Bll.Provider.MySql.Entity.Title", b =>
                {
                    b.HasOne("Statistic.Bll.Provider.MySql.Entity.ColorSql", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statistic.Bll.Provider.MySql.Entity.Tag", "Tag")
                        .WithMany("Tittles")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Statistic.Bll.Provider.MySql.Entity.Tag", b =>
                {
                    b.Navigation("Statistics");

                    b.Navigation("Tittles");
                });
#pragma warning restore 612, 618
        }
    }
}
